### ISSUE TITLE
Review !

### ISSUE THREAD

**Issue by Christiantaguejou** [PolytechLyon/isi3-tp2-visiteur-lombardo-taguejou-tp2#1]

**Comment by Slashgear** [comment]
Les schéma => ❤️ 

- Pouvez vous m'expliquer le cas d'utilisation du pattern visiteur ?

- On range les choses en packages (:warning:  les packages en java c'est en minuscule)

- Ok pour votre gestion de la priorité

**Comment by Christiantaguejou** [comment]
Le pattern visiteur permet de définir de nouvelles opération sans avoir à modifier le code existant. En implémentant l'interface Visitable, la nouvelle opération pourra être visiter.

**Comment by Christiantaguejou** [comment]
Le pattern visiteur permet de séparer les données et les traitements associés à ces données. Dans notre cas, les classes qui implémentent l'interface Visiteur contiennent les traitements des données et ceux implémentant Visitables contiennent les données. L'intérêt de ce pattern est qu'on peut modifier ou ajouter des visiteurs en ne travaillant que sur le code qui nous intéresse.
Ainsi, on utilise le pattern Visiteur quand on veut associer un traitement spécifique à chaque élément tout en faisant en sorte que l'ajout ou la modification d'un traitement ne modifie pas les classes existantes.

**Comment by Slashgear** [comment]
Ok c'est bon pour moi 👌
